language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: i0HPrLNcUtAkHtScS98u9Ch+BmclxB69fd5oR+fTDLXIPzgEMhV/fljtvqQY18Ty2Oya/1u63ZrMlNAZfdxmuXh+UcxluO6EWOml0n9qfqRqazH0z/xL6P/E1PGUGujgzOh3gYYfPvOFTTpWKdsC+oHovVpW/FYNA6dJvcoOPN0=
