language: r
sudo: required

r_github_packages:
- jimhester/covr
- ropensci/oai

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: i0HPrLNcUtAkHtScS98u9Ch+BmclxB69fd5oR+fTDLXIPzgEMhV/fljtvqQY18Ty2Oya/1u63ZrMlNAZfdxmuXh+UcxluO6EWOml0n9qfqRqazH0z/xL6P/E1PGUGujgzOh3gYYfPvOFTTpWKdsC+oHovVpW/FYNA6dJvcoOPN0=
